backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/assets/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "assets/" # The src attribute for uploaded media will begin with /images/uploads
